---
title: "Homework 1"
subtitle: "STAT 341"
author: "WRITE YOUR NAME HERE"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{setspace, diagbox} 
---
\onehalfspacing

* * * 

### Instructions

- This homework is due in Gradescope on Wednesday Oct 15 by midnight PST. There is a 15 minute grace period and submissions made during this time will not be marked as late. Any work submitted past this period is considered late.  

- Please answer the following questions in the order in which they are posed. \textbf{Be sure to support your work and show your steps.}

- Don't forget to (i) make a local copy of this document for your work and to (ii) knit the document frequently to make sure there are no compilation errors. 

- When you are done, download the PDF file and submit it in Gradescope. \textbf{Do not forget to tag your answers to every sub-part of every question. We will take off 10\% for every part that is not tagged}

* * *


### Exercises 

1. (White chip, blue chip) An urn contains four red chips, three white chips,
and two blue chips. A random sample of size 3 is drawn
without replacement. Let $X$ denote the number of white
chips in the sample and $Y$ the number of blue chips. Fill in the table of the joint PMF of $\langle X, Y \rangle$. Please use inline code as shown in quiz section.

  
    
    \begin{table}[h]
    \centering
    \caption{Joint PMF for $X$ and $Y$}
    \begin{tabular}{|c|c|c|c|c|} \hline
    \backslashbox{$y$}{$x$} &  &  &  &  \\ \hline
     &  &  &  &  \\ \hline
     & &  & & \\ \hline
     & & & & \\ \hline
    \end{tabular}
    \end{table}
    
    
2. (Grades) A physics professor has just given an exam to fifty students enrolled in a thermodynamics class. From past experience, she has reason to believe that the scores will be normally distributed with $\mu = 80.0$ and $\sigma = 5.0$. Students scoring ninety or above will receive A’s, between eighty and ninety, B’s and the rest will get a C.

a. The random variables $X$ and $Y$ follow a trinomial distribution under certain assumptions. In other words, $\langle X, Y \rangle \sim Trinom(n, \pi_1, \pi_2)$. What are $n$, $\pi_1$ and $\pi_2$? Also state the assumption.

    Note: please do any calculations for $\pi_1$ and $\pi_2$ in a code chunk, ideally by defining variables and assigning them values and don't forget to print answers. 

b. Use `dmultinom` to find the probability that 5 students will get an A and 3 will get a B. Be sure to do this in a code chunk and print the answer.

c. Find the probability that more than 5 students will get an A. Clearly state the distribution you will use for this calculation. Be sure to do your calculations in a code chunk with the answer printed.

   
3. (Marginalizing) Let $X$ and $Y$ be discrete random variables with joint PMF 
$$f(x, y) = \left(\frac{\lambda}{2} \right)^{y} \frac{e^{-\lambda}}{x! \:(y-x)!}$$

    where $x$ and $y$ are (non-negative) integers and $0 \leq x \leq y$. That is, $x, y = 0, 1, 2, 3, \dots$ but with the constraint $0 \leq x \leq y$.

    Determine $f_2(y)$, the marginal distribution of $Y$. Is this a familiar distribution? If so, which one?  Show the steps.
   
    *Hint*: you will need to use the Binomial theorem with a = 1 and b = 1 to perform the summation over $x$. 



4. (Seedlings)  A plant releases $X$ seeds. With probability $\alpha$ it releases $m$ seeds,  and with probability $1-\alpha$ it releases $M$ seeds, where $0 < m < M$ are known integers:
$$P(X = m) = \alpha, \qquad P(X = M) = 1 - \alpha.$$
Suppose each seed germinates with probability $\pi$, independently of all other seeds. Let $Y$ be the resulting number of seedlings.

a. What is $f(y|x)$, the conditional distribution of $Y$ given $X = x$? Be sure to write the PMF. (Don't forget to include the support and also explain your answer)

b. Suppose $X = m$. How many seeds should you expect will germinate? Please write your answer in a full sentence with your reasoning. (You can just state any results you use)

c. Repeat part b when $X = M$.

d. On average over the two $X$ values, how many seed should you expect will germinate then?  
