---
title: "Take Home 3"
subtitle: "Winter 2022"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This homework is due on Tuesday Feb 1 by midnight PST.

\textbf{Instructions}: Follow each one diligently. \textbf{No exceptions.}
\hrule
\begin{enumerate}
	\item Please type your answers and upload as a PDF in Gradescope. If you prefer to write your answers, we will accept handwritten work provided it is legible. If you decide to go this route, be sure to \href{https://www.camscanner.com)}{scan} and upload a single file.  
	\item Write your full name (as it appears in the grade book) on the first page, preferably as a running header on each page.
	\item Answer the questions in order and number them as I have here. 
	\item \textbf{Write complete answers which includes justifications for steps and/or references to results you use. This is really important.You all need to practice writing mathematical answers - define notation, explain what you are doing, cite any rules, etc. }
	\item Clearly indicate your final answer. Put a frame around it where appropriate.
\end{enumerate}
\hrule 

1. Let $x_1, x_2, x_3$ be independent observations of a random variable $X$ from the PDF
$$f(x) = \frac{1}{2} e^{-|x-\theta|}, \ \ -\infty < x < \infty$$
and $\theta$ is an unknown parameter of the distribution. Derive the method of moment estimate of $\theta$.

2. Pruim problem 4.7 on page 333. **Be sure to label the parts, answer the questions clearly and show your code and output neatly.**

3. The dataset we will be using is called $airbnb\_price.csv$ and was downloaded from the Kaggle database.
   a. Draw the population distribution of \texttt{price}. Calculate the population mean $\mu$ and standard deviation $\sigma$.
   b. Simulate the sampling distribution of the mean of \emph{price}. Examine the impact of increasing sample size by considering samples of size 10, 25 and 100. (Use a large number of replications, at least 5,000). Make a density histogram of the values generated in each case, with a density curve of a normal distribution with mean $\mu$ and standard deviation $\sigma/\sqrt{n}$ superimposed on it. Write no more than one paragraph describing the results of your simulation. 
   
**We are mainly going to read your paragraph and see the plots. But don't forget to include your code neatly.**

4. Please read the \href{https://www.king5.com/article/news/health/coronavirus/uw-medicine-limit-covid-testing/281-7547b3d5-f3c9-4c55-a926-39cdf5903aed}{article} titled "UW Medicine limiting COVID 19 testing to those with symptoms, known exposures. This is a timely article which covers a problem you saw in STAT 340. You now know these things have a real application! So let's do this problem again for fun!

   As noted in the article, the high COVID positivity rate is important because UW Medicine tests COVID-19 samples by pooling samples. Pooling involves taking a small portion of four or five samples and mixing them into one sample and then testing that one sample for COVID-19. If a pool sample is positive, each sample in that pool is taken and tested individually to see which sample, or samples, was positive. 

   Therefore within each group, pooling half of each blood sample requires only one test if all samples are  negative, while if at least one is positive, the other half of each blood sample can be tested individually. In this case, we would be conducting $m+1$ different tests. 
 
   
   a. Suppose $X_i$ is the number of tests conducted in group $i$. Show that 
     \begin{eqnarray*}
      E\left[X_i \right] &=& (1-p)^{m} + (m+1) (1-(1-p)^{m}), \\
      Var\left[X_i \right] &=& m^2 (1-p)^{m} (1-(1-p)^{m}).
      \end{eqnarray*}
    
   b. Let $N$ denote the total number of tests performed. That is $$N = \sum\limits_{i=1}^{k} X_i.$$ Find $E\left[N \right]$ and $Var\left[N \right]$. Clearly state assumptions you are making to perform the calculations.
    
   c.  Let's assume UW Medicine receives $n=15,000$ blood samples. Let's also assume that the blood samples are grouped into $k=3,000$ groups of $m=5$ each. Make a plot (properly labeled) which shows how the expected number of tests varies as a function of $p$, the positivity rate. Try a sequence of values for $p$ from 5\% to 45\% in some suitable increments. 